// Code generated by prisma-go-tools. DO NOT EDIT.

package entity

import (
	"time"
)

type Product struct {
	ID        string     `db:"id" json:"id,omitempty"`
	Name      string     `db:"name" json:"name,omitempty"`
	Price     float64    `db:"price" json:"price,omitempty"`
	CreatedAt time.Time  `db:"created_at" json:"created_at,omitempty"`
	DeletedAt *time.Time `db:"deleted_at" json:"deleted_at,omitempty"`
}

type Error struct {
	ID         string     `db:"id" json:"id,omitempty"`
	Message    string     `db:"message" json:"message,omitempty"`
	Type       string     `db:"type" json:"type,omitempty"`
	StackTrace string     `db:"stack_trace" json:"stack_trace,omitempty"`
	Metadata   string     `db:"metadata" json:"metadata,omitempty"`
	CreatedAt  time.Time  `db:"created_at" json:"created_at,omitempty"`
	DeletedAt  *time.Time `db:"deleted_at" json:"deleted_at,omitempty"`
}
