// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package webscraper

import (
	"github.com/danielmesquitta/supermarket-web-scraper/internal/app/webscraper/handler"
	"github.com/danielmesquitta/supermarket-web-scraper/internal/config"
	"github.com/danielmesquitta/supermarket-web-scraper/internal/pkg/validator"
	"github.com/danielmesquitta/supermarket-web-scraper/internal/provider/db/sqlite"
)

// Injectors from wire.go:

func New() *WebScraper {
	validation := validator.New()
	env := config.LoadConfig(validation)
	db := sqlite.New(env)
	handlerHandler := handler.New(env, db)
	webScraper := Build(handlerHandler)
	return webScraper
}
