// Code generated by prisma-go-tools. DO NOT EDIT.

package schema

import "fmt"

type tableError string

func (t tableError) Table() string {
	return string(t)
}

func (t tableError) ColumnAll() string {
	return fmt.Sprintf("%s.*", t)
}

func (t tableError) ColumnCreatedAt() string {
	return fmt.Sprintf("%s.created_at", t)
}

func (t tableError) ColumnDeletedAt() string {
	return fmt.Sprintf("%s.deleted_at", t)
}

func (t tableError) ColumnID() string {
	return fmt.Sprintf("%s.id", t)
}

func (t tableError) ColumnMessage() string {
	return fmt.Sprintf("%s.message", t)
}

func (t tableError) ColumnMetadata() string {
	return fmt.Sprintf("%s.metadata", t)
}

func (t tableError) ColumnStackTrace() string {
	return fmt.Sprintf("%s.stack_trace", t)
}

func (t tableError) ColumnType() string {
	return fmt.Sprintf("%s.type", t)
}

const Error = tableError("errors")

type tableProduct string

func (t tableProduct) Table() string {
	return string(t)
}

func (t tableProduct) ColumnAll() string {
	return fmt.Sprintf("%s.*", t)
}

func (t tableProduct) ColumnCreatedAt() string {
	return fmt.Sprintf("%s.created_at", t)
}

func (t tableProduct) ColumnDeletedAt() string {
	return fmt.Sprintf("%s.deleted_at", t)
}

func (t tableProduct) ColumnID() string {
	return fmt.Sprintf("%s.id", t)
}

func (t tableProduct) ColumnName() string {
	return fmt.Sprintf("%s.name", t)
}

func (t tableProduct) ColumnPrice() string {
	return fmt.Sprintf("%s.price", t)
}

const Product = tableProduct("products")
