// Code generated by prisma-go-tools. DO NOT EDIT.

package schema

import "fmt"

type tableError string

func (t tableError) String() string {
	return string(t)
}

func (t tableError) All() string {
	return fmt.Sprintf("%s.*", t)
}

func (t tableError) CreatedAt() string {
	return fmt.Sprintf("%s.created_at", t)
}

func (t tableError) DeletedAt() string {
	return fmt.Sprintf("%s.deleted_at", t)
}

func (t tableError) ID() string {
	return fmt.Sprintf("%s.id", t)
}

func (t tableError) Message() string {
	return fmt.Sprintf("%s.message", t)
}

func (t tableError) Metadata() string {
	return fmt.Sprintf("%s.metadata", t)
}

func (t tableError) StackTrace() string {
	return fmt.Sprintf("%s.stack_trace", t)
}

func (t tableError) Type() string {
	return fmt.Sprintf("%s.type", t)
}

const Error = tableError("errors")

type tableProduct string

func (t tableProduct) String() string {
	return string(t)
}

func (t tableProduct) All() string {
	return fmt.Sprintf("%s.*", t)
}

func (t tableProduct) Code() string {
	return fmt.Sprintf("%s.code", t)
}

func (t tableProduct) CreatedAt() string {
	return fmt.Sprintf("%s.created_at", t)
}

func (t tableProduct) DeletedAt() string {
	return fmt.Sprintf("%s.deleted_at", t)
}

func (t tableProduct) ID() string {
	return fmt.Sprintf("%s.id", t)
}

func (t tableProduct) Name() string {
	return fmt.Sprintf("%s.name", t)
}

func (t tableProduct) Price() string {
	return fmt.Sprintf("%s.price", t)
}

const Product = tableProduct("products")
